### ISSUE TITLE
Repository does not contain a License

### ISSUE THREAD

**Issue by patryk-tech** [reddit-habs/nhlapi#1]
Hey! I am really fascinated by the way you solved the JSON->`nested.python.objects` when dealing with the NHL API, and would love to use that in one of my MIT licensed projects, but as the repo has no license information, I cannot. Could you add a license, please? Thanks.

**Comment by sbstp** [comment]
Hey! I'm glad someone uses this. I added the `Zlib` license to the project, which is a permissive license that I really enjoy because of it's simple terms. Don't hesitate to ask questions or suggest improvements!

**Comment by patryk-tech** [comment]
Awesome, thanks :)

If all goes according to plan, I'll be posting a project that does use it on reddit before next season.
