### ISSUE TITLE
Simplifying imports?

### ISSUE THREAD

**Issue by patryk-tech** [reddit-habs/nhlapi#3]
Hey,

the way imports currently work means that to use things like `NHLAPI`, you need to explicitly import it from the correct file.

    from nhlapi.endpoints import NHLAPI
    from nhl.io import Client

What would you say to simplifying this by adding the classes to `__init__.py`? I'd personally import `Client` as `IOClient` (synchronous) or `AIOClient` (async). In fact, I [have added it to my fork](https://github.com/patryk-tech/nhlapi/blob/init-imports/nhlapi/__init__.py) (branched from `improvements`).

This simplifies the imports a bit.

    # single import, but it is a bit slower as it imports dependencies - then again,
    # not considerably slower than from nhlapi.somefile import XXX
    import nhlapi

    # client = nhlapi.io.Client()  # the classic way
    client = nhlapi.IOClient  # same result
    api = nhlapi.NHLAPI(client)

Alternatively, you can also used named imports.

    from nhlapi import AIOClient, NHLAPI
    # from nhlapi import *  # this also works, though I am not a fan of import *
    api = NHLAPI(AIOClient())

PS: Also, not sure if you get notifications on closed requests (most of my git experience is in a team of one); but I have responded to your question on my pull request.

**Comment by sbstp** [comment]
Yes I get notifications. I think this is a good idea. Right now, I'm refactoring the props API to avoid collisions between objects with a `["keys"]` entry and the method `keys()` for instance.

One caveat I would add is that the `AIOClient` should not exist if `aiohttp` is not installed, same for the `IOClient`.

It can be solved easily with something like this:

```python3
try:
  import aiohttp
  class AIOClient:
     ...
except ImportError:
  pass
```

Also I'm planning on adding a method to the client named `raw` that makes it easily to perform/format custom requests because the API has so many different ways of being called.

Btw: if you want to add highlighting to your code blocks https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by patryk-tech** [comment]
> One caveat I would add is that the `AIOClient` should not exist if `aiohttp` is not installed, same for the `IOClient`.

Good catch. I explicitly install it, so it was easy to overlook.

> highlighting

Thanks for the tip. Trying to spend more time in git{,hub,lab} and less on reddit, so not fully used to the syntax yet.

**Comment by sbstp** [comment]
Hey, I'd like to have your opinion on this new API.

```python3
api = NHLAPI(Client())
x = api.get("https://statsapi.web.nhl.com/api/v1/teams/{0}", 8, expand=["team.roster", "team.stats"])
```

The `*args` are replaced in the URL (8 in this case) and the `**kwargs` become query string parameters (expand). It makes it really easy to create a custom end point.

**Comment by sbstp** [comment]
Full URL is not mandatory also, this works:

```python3
x = api.get("api/v1/teams/{0}", 8, expand=["team.roster", "team.stats"])
```

**Comment by patryk-tech** [comment]
That looks great! Haven't had a chance to test _all_ of it yet. I noticed a few minor issues, and sent a pull request (particularly, the methods weren't updated to reflect the `API_BASE_URL` change, though there may be better ways to build the URL). At least, the tests now pass.

Another minor thing, the project description contains a Docs link to https://docs.sbstp.ca/nhlapi/endpoints.html ... I believe it should be pointing to https://docs.sbstp.ca/nhlapi/index.html instead.

**Comment by sbstp** [comment]
Should be ok now!
